# Generated by Django 4.1.1 on 2024-12-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_directorgeneral_laboratorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'verbose_name': 'Director General', 'verbose_name_plural': 'Directores Generales'},
        ),
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='cuidad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
