# Generated by Django 4.1.1 on 2024-12-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_actualizado_campos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratorio',
            old_name='cuidad',
            new_name='ciudad',
        ),
    ]
